package kotlinmud.item.type

enum class Material(val value: String) {
    ORGANIC("organic"),
    MINERAL("mineral"),
    METAL("metal"),
    IRON("iron"),
    GOLD("gold"),
    WOOD("wood"),
    RUBBER("rubber"),
    LEATHER("leather"),
    COMPOSITE("composite"),
    TEXTILE("textile"),
    PAPER("paper"),
    NONCORPOREAL("noncorporeal"),
    LIQUID("liquid"),
    VULN_SOUND("vuln_sound"),
    FLAMMABLE("flammable"),
    CONDUCTOR("conductor"),
    CONCRETE("concrete"),
    GLASS("glass"),
    STONE("stone"),
    VULN_SHATTER("vuln_shatter"),
    VULN_COLD("vuln_cold"),
    VULN_RUST("vuln_rust"),
    VULN_SLICE("vuln_slice"),
    FIREPROOF("fireproof"),
    RUSTPROOF("rustproof"),
    SLICEPROOF("sliceproof"),
    ACIDPROOF("acidproof"),
    DIAMOND("diamond"),
    TIN("tin"),
    COPPER("copper"),
}
