package kotlinmud.mob.skill.type

enum class SkillType(val value: String) {
    BASH("bash"),
    BERSERK("bererk"),
    BITE("bite"),
    BLEED("bleed"),
    BLESS("bless"),
    BREATHE("breathe"),
    DIRT_KICK("dirt kick"),
    FEAR("fear"),
    HEX("hex"),
    TRIP("trip"),
    SHIELD_BLOCK("shield block"),
    HAMSTRING("hamstring"),
    ACCLIMATE("acclimate"),
    CONNIVE("connive"),
    ALCHEMY("alchemy"),
    ANOINTMENT("anointment"),
    AURA_OF_VALOR("aura of valor"),
    RIDING("riding"),
    RAGE("rage"),
    ESPIONAGE("espionage"),
    IMBUE("imbue"),
    ENDURANCE("endurance"),
    BARBARIAN_RAGE("barbarian rage"),
    FOCUS("focus"),
    SPELLCRAFT("spellcraft"),
    GARROTE("garrote"),
    GRAB("grab"),
    DUAL_WIELD("dual wield"),
    INFILTRATE("infiltrate"),
    TUMBLING("tumbling"),
    CUT_PURSE("cut purse"),
    MEDITATION("meditation"),
    FAST_HEALING("fast healing"),
    INFUSE("infuse"),
    BACKSTAB("backstab"),
    DODGE("dodge"),
    ENVENOM("envenom"),
    HIDE("hide"),
    PEEK("peek"),
    SNEAK("sneak"),
    SNATCH("snatch"),
    SLICE("slice"),
    STEAL("steal"),
    TRAP("trap"),
    SHARPEN("sharpen"),
    SCRIBE("scribe"),
    DISARM("disarm"),
    KICK("kick"),
    PARRY("parry"),
    RESCUE("rescue"),
    SECOND_ATTACK("second attack"),
    THIRD_ATTACK("third attack"),
    FOURTH_ATTACK("fourth attack"),
    TAIL("tail"),

    // damage enhancers
    CLEAVE("cleave"),
    BLUDGEON("bludgeon"),
    ENHANCED_CRITICAL("enhanced critical"),
    ENHANCED_DAMAGE("enhanced damage"),

    // weapons
    AXE("axe"),
    DAGGER("dagger"),
    FLAIL("flail"),
    UNARMED("unarmed"),
    MACE("mace"),
    POLEARM("polearm"),
    SPEAR("spear"),
    STAFF("staff"),
    SWORD("sword"),
    WHIP("whip"),
    WAND("wand"),

    // spells
    STEEL_SKIN("steel skin"),
    DIAMOND_SKIN("diamond skin"),
    DUST_STORM("dust storm"),
    HOLY_CHANT("holy chant"),
    FORGET("forget"),
    ENERVATION("enervation"),
    FUMBLE("fumble"),
    BLUR("blur"),
    INVISIBILITY("invisibility"),
    CURSE("curse"),

    // healing
    CURE_LIGHT("cure light"),
    CURE_SERIOUS("cure serious"),
    HEAL("heal"),

    // curative
    CURE_POISON("cure poison"),
    CURE_BLINDNESS("cure blindness"),
    REMOVE_CURSE("remove curse"),

    // malediction
    BLIND("blind"),

    // enhancement
    GIANT_STRENGTH("giant strength"),
    HASTE("haste"),
}
