package kotlinmud.io

enum class Syntax(val syntax: String) {
    COMMAND("command"),
    SUBCOMMAND("subcommand"),
    CAST("cast"),
    RECIPE("recipe"),
    ITEM_TO_HARVEST("item to harvest"),
    DIRECTION_TO_EXIT("direction to exit"),
    DIRECTION_WITH_NO_EXIT("direction with no exit"),
    ITEM_IN_ROOM("item in room"),
    ITEM_IN_INVENTORY("item in inventory"),
    AVAILABLE_ITEM_INVENTORY("available item inventory"),
    ITEM_IN_AVAILABLE_INVENTORY("item"),
    EQUIPPED_ITEM("equipped item"),
    EQUIPMENT_IN_INVENTORY("equipment in inventory"),
    SPELL_FROM_HEALER("spell from healer"),
    ITEM_FROM_MERCHANT("item from merchant"),
    ITEM_TO_SELL("item to sell"),
    MOB_IN_ROOM("mob in room"),
    AVAILABLE_NOUN("available noun"),
    TARGET_MOB("target mob"),
    OPTIONAL_TARGET("optional target"),
    DOOR_IN_ROOM("door in room"),
    FREE_FORM("free form"),
    SPELL("spell"),
    PLAYER_MOB("player mob"),
    AVAILABLE_DRINK("available drink"),
    AVAILABLE_FOOD("available food"),
    TRAINABLE("trainable"),
    SKILL_TO_PRACTICE("skill to practice"),
    NOOP("noop"),
}
