name: Run Gradle Tests
on:
  push:
    tags:
      - '*'
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u danielmunro --password-stdin
      - name: Build
        run: docker build -t ghcr.io/danielmunro/kotlinmud:${{ github.ref_name }} .
      - name: Push
        run: docker push ghcr.io/danielmunro/kotlinmud:${{ github.ref_name }}
